services:
  grocery-db:
    image: postgres:15-alpine
    container_name: grocery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grocery
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: grocery-migrate
    env_file:
      - ./api/.env.test
    depends_on:
      grocery-db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: grocery-api
    env_file:
      - ./api/.env.test
    ports:
      - "4000:4000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: >
      sh -c "node dist/main.js"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: grocery-app
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:
